# Generated by Django 3.1.4 on 2022-11-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todochoice',
        ),
        migrations.AddField(
            model_name='todolistitem',
            name='choices',
            field=models.CharField(default='personal', max_length=20),
        ),
    ]
